#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt',             '1.1.2'
cookbook 'build-essential', '1.0.0'
cookbook 'rvm',
	:git => 'git://github.com/fnichol/chef-rvm.git', :ref => 'v0.9.0'
cookbook 'unicorn'
cookbook 'nginx'
cookbook 'git'
cookbook 'aws'
cookbook 'logrotate'
